#!/bin/bash
set -e

echo "=== Saku Worker Docker セットアップ ==="
echo ""

# Docker インストール確認
if ! command -v docker &>/dev/null; then
    echo "❌ Docker がインストールされていません"
    echo "→ https://docs.docker.com/desktop/install/mac-install/"
    exit 1
fi
if ! docker compose version &>/dev/null 2>&1 && ! command -v docker-compose &>/dev/null; then
    echo "❌ Docker Compose が見つかりません"
    exit 1
fi
echo "✅ Docker: $(docker --version)"
echo ""

# .env ファイル生成
if [ -f .env ]; then
    echo "⚠️  既存の .env ファイルを検出しました"
    read -r -p "上書きしますか？ (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "スキップ → ビルドへ"
        source .env 2>/dev/null || true
        goto_build=1
    fi
fi

if [ -z "$goto_build" ]; then
    echo "--- [必須] Discord Bot Token ---"
    echo "取得場所: https://discord.com/developers/applications"
    echo ""
    read -r -p "ぷーちゃん Discord Bot Token: " pu_chan_token
    [ -z "$pu_chan_token" ] && echo "❌ Token が空です" && exit 1

    read -r -p "ピノ Discord Bot Token: " pino_token
    [ -z "$pino_token" ] && echo "❌ Token が空です" && exit 1

    echo ""
    echo "--- [オプション] LLM API Keys ---"
    echo "空のまま Enter でスキップできます"
    echo ""

    read -r -p "ANTHROPIC_API_KEY (Claude): " anthropic_key
    if [ -z "$anthropic_key" ]; then
        echo "  → スキップされました"
    fi

    read -r -p "OPENAI_API_KEY (GPT): " openai_key
    if [ -z "$openai_key" ]; then
        echo "  → スキップされました"
    fi

    read -r -p "GEMINI_API_KEY (Gemini): " gemini_key
    if [ -z "$gemini_key" ]; then
        echo "  → スキップされました"
    fi

    echo ""
    echo "--- [オプション] アクセス設定 ---"
    echo "Tailscale 経由でアクセスする場合は IP を入力"
    echo "Mac Studio 本体から使う場合はそのまま Enter"
    read -r -p "Tailscale IP (デフォルト: localhost): " tailscale_ip
    DASHBOARD_HOST="${tailscale_ip:-localhost}"

    cat > .env << ENV
# ⚠️  このファイルは Git にコミットしないこと
# Generated by setup.sh on $(date +"%Y-%m-%d %H:%M:%S")

# ====== [必須] Discord Bot Tokens ======
# 取得先: https://discord.com/developers/applications
PU_CHAN_DISCORD_TOKEN=${pu_chan_token}
PINO_DISCORD_TOKEN=${pino_token}

# ====== [オプション] LLM API Keys ======
ANTHROPIC_API_KEY=${anthropic_key}
OPENAI_API_KEY=${openai_key}
GEMINI_API_KEY=${gemini_key}

# ====== Dashboard アクセス設定 ======NEXT_PUBLIC_API_URL=http://${DASHBOARD_HOST}:9000
DASHBOARD_HOST=${DASHBOARD_HOST}
ENV

    echo ""
    echo "✅ .env を作成しました"
fi

# ディレクトリ確認
mkdir -p defaults pu-chan pino shared/logs shared/config

echo ""
echo "--- ビルド & 起動 ---"
docker compose build
docker compose up -d

echo ""
echo "=== ✅ セットアップ完了 ==="
echo ""
echo "📊 Dashboard: http://${DASHBOARD_HOST}:3000"
echo "🔌 API: http://${DASHBOARD_HOST}:9000"
echo ""
echo "🤖 Agents:"
echo "  ぷーちゃん: http://${DASHBOARD_HOST}:8001"
echo "  ピノ: http://${DASHBOARD_HOST}:8002"
echo ""
echo "🔀 Router: http://${DASHBOARD_HOST}:8080"
echo ""
echo "📋 よく使うコマンド:"
echo "  ログ確認: docker compose logs -f [pu-chan|pino|saku-router|saku-dashboard-api]"
echo "  停止: docker compose down"
echo "  再起動: docker compose restart"
echo ""
