#!/bin/bash
set -e

echo "=== Saku Worker Docker セットアップ ==="
echo ""

# Docker インストール確認
if ! command -v docker &>/dev/null; then
    echo "❌ Docker がインストールされていません"
    echo "→ https://docs.docker.com/desktop/install/mac-install/"
    exit 1
fi
if ! docker compose version &>/dev/null 2>&1 && ! command -v docker-compose &>/dev/null; then
    echo "❌ Docker Compose が見つかりません"
    exit 1
fi
echo "✅ Docker: $(docker --version)"
echo ""

# .env ファイル生成
if [ -f .env ]; then
    echo "⚠️  既存の .env ファイルを検出しました"
    read -r -p "上書きしますか？ (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "スキップ → ビルドへ"
        goto_build=1
    fi
fi

if [ -z "$goto_build" ]; then
    echo "--- 必須: Discord Bot Token ---"
    echo ""
    read -r -p "ぷーちゃん Discord Bot Token: " pu_chan_token
    [ -z "$pu_chan_token" ] && echo "❌ Token が空です" && exit 1

    read -r -p "ピノ Discord Bot Token: " pino_token
    [ -z "$pino_token" ] && echo "❌ Token が空です" && exit 1

    echo ""
    echo "--- オプション: LLM API Keys ---"
    echo "(空のまま Enter でスキップ可能)"
    echo ""
    read -r -p "ANTHROPIC_API_KEY (Claude): " anthropic_key
    read -r -p "OPENAI_API_KEY (GPT): " openai_key
    read -r -p "GEMINI_API_KEY (Gemini): " gemini_key

    echo ""
    echo "--- Dashboard アクセス設定 ---"
    echo "(Tailscale 経由でアクセスする場合は IP を入力)"
    echo "(Mac Studio 本体から使う場合は Enter でスキップ)"
    read -r -p "Tailscale IP または空白 (localhost になります): " tailscale_ip
    DASHBOARD_HOST="${tailscale_ip:-localhost}"

    cat > .env << ENV
# ⚠️  このファイルは Git にコミットしないこと
# Generated by setup.sh $(date +"%Y-%m-%d %H:%M:%S")

# ====== エージェント Discord Bot Tokens ======
PU_CHAN_DISCORD_TOKEN=${pu_chan_token}
PINO_DISCORD_TOKEN=${pino_token}

# ====== LLM API Keys (router 経由で使用) ======
ANTHROPIC_API_KEY=${anthropic_key}
OPENAI_API_KEY=${openai_key}
GEMINI_API_KEY=${gemini_key}

# ====== Dashboard アクセス設定 ======
NEXT_PUBLIC_API_URL=http://${DASHBOARD_HOST}:9000
DASHBOARD_HOST=${DASHBOARD_HOST}
ENV

    echo ""
    echo "✅ .env を作成しました"
fi

# ディレクトリ確認
mkdir -p defaults pu-chan pino shared/logs shared/config

echo ""
echo "--- ビルド & 起動 ---"
docker compose build
docker compose up -d
DASHBOARD_HOST="${DASHBOARD_HOST:-localhost}"

echo ""
echo "=== セットアップ完了 ==="
echo ""
echo "📊 Dashboard:"
echo "  http://${DASHBOARD_HOST}:3000"
echo ""
echo "🤖 Agents:"
echo "  ぷーちゃん: http://${DASHBOARD_HOST}:8001"
echo "  ピノ:       http://${DASHBOARD_HOST}:8002"
echo ""
echo "🔀 Router:"
echo "  http://${DASHBOARD_HOST}:8080"
echo ""
echo "📋 ログ確認:"
echo "  docker compose logs -f pu-chan"
echo "  docker compose logs -f pino"
echo ""
echo "⛔ 停止:"
echo "  docker compose down"
