#!/bin/bash
set -e

echo "=== Saku Worker Docker セットアップ ==="
echo ""

# Docker インストール確認
if ! command -v docker &>/dev/null; then
    echo "❌ Docker がインストールされていません"
    echo "→ https://docs.docker.com/desktop/install/mac-install/ でインストールしてください"
    exit 1
fi

if ! command -v docker-compose &>/dev/null && ! docker compose version &>/dev/null 2>&1; then
    echo "❌ Docker Compose が見つかりません"
    exit 1
fi

echo "✅ Docker: $(docker --version)"
echo ""

# .env ファイル生成
if [ -f .env ]; then
    echo "⚠️  既存の .env ファイルを検出しました"
    read -r -p "上書きしますか？ (y/N): " overwrite
    [[ "$overwrite" =~ ^[Yy]$ ]] || { echo "スキップ"; goto_build=1; }
fi

if [ -z "$goto_build" ]; then
    echo ""
    echo "--- Discord Bot Token を入力してください ---"
    echo ""

    read -r -p "ぷーちゃん Discord Bot Token: " pu_chan_token
    if [ -z "$pu_chan_token" ]; then
        echo "❌ Token が空です"; exit 1
    fi

    read -r -p "ピノ Discord Bot Token: " pino_token
    if [ -z "$pino_token" ]; then
        echo "❌ Token が空です"; exit 1
    fi

    cat > .env << ENV
# ⚠️  このファイルは Git にコミットしないこと
# Generated by setup.sh

PU_CHAN_DISCORD_TOKEN=${pu_chan_token}
PINO_DISCORD_TOKEN=${pino_token}

# OpenClaw Gateway Token（オプション: 接続認証用）
# OPENCLAW_GATEWAY_TOKEN=your-secret-token-here
ENV

    echo ""
    echo "✅ .env を作成しました"
fi

# defaults ディレクトリ確認
mkdir -p defaults pu-chan pino shared/logs shared/config

# Tailscale IP 取得
TAILSCALE_IP=""
if command -v tailscale &>/dev/null; then
    TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || true)
fi
if [ -z "$TAILSCALE_IP" ]; then
    TAILSCALE_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
fi

echo ""
echo "--- ビルド & 起動 ---"
docker compose build
docker compose up -d

echo ""
echo "=== セットアップ完了 ==="
echo ""
echo "アクセス URL:"
echo "  ぷーちゃん: http://localhost:8001"
echo "  ピノ:       http://localhost:8002"
if [ -n "$TAILSCALE_IP" ]; then
    echo ""
    echo "Tailscale 経由:"
    echo "  ぷーちゃん: http://${TAILSCALE_IP}:8001"
    echo "  ピノ:       http://${TAILSCALE_IP}:8002"
fi
echo ""
echo "ログ確認:"
echo "  docker compose logs -f pu-chan"
echo "  docker compose logs -f pino"
echo ""
echo "停止:"
echo "  docker compose down"
